name = "ITensorGaussianMPS"
uuid = "2be41995-7c9f-4653-b682-bfa4e7cebb93"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.1.13"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Compat = "3.40.0, 4"
ITensorMPS = "0.3"
ITensors = "0.7, 0.8, 0.9"
LinearAlgebra = "1.10"
julia = "1.10"
